###admin can delete any user
delete http://localhost:4000/admin-api/user/67a6f112f2525dcee8f9c9d6

###admin can delete any publication
delete http://localhost:4000/admin-api/publication/67a6f408f4a7cbe7e13aeb07

###admin can delete any patent
delete http://localhost:4000/admin-api/patent/67a6f420f4a7cbe7e13aeb08

###admin can delete any fundingProposal
delete http://localhost:4000/admin-api/fundingProposal/67a6f42cf4a7cbe7e13aeb09

###Admin  UPDATE publication 
put http://localhost:4000/admin-api/publication
Content-Type: application/json

{
  "username": "vamshi",
  "typeOfPublication": "journal",
  "nameOfJournal": "test",
  "titleOfPaper": "newtest",
  "dateOfPublication": "2025-02-05",
  "indexing": "test",
  "authorPosition": "test",
  "linkForProof": "test.com",
  "teamno": 1
}

###Admin  UPDATE patent 
put http://localhost:4000/admin-api/patent
Content-Type: application/json

{
  "titleOfPatent": "test",
  "nameOfInventor": "vamshi",
  "status": "pending",
  "username": "vamshi",
  "teamno": 1
}


###Admin  UPDATE funding prop 
put http://localhost:4000/admin-api/funding
Content-Type: application/json

{
  "titleOfProposal": "test",
  "detailsOfPiCopi": "test",
  "fundingAgency": "test",
  "amount": "20000000",
  "fundStatus": "test",
  "teamno": 1
}


###Admin creating a user
